import turtle
import math

screen = turtle.Screen()
screen.bgcolor("skyblue")

ebel_frank = turtle.Turtle()
ebel_frank.color("black")
ebel_frank.shape("turtle")
ebel_frank.speed(4)


class MySquare:
    def Square():
        ebel_frank.fillcolor("red")
        ebel_frank.begin_fill()
        ebel_frank.forward(20)
        ebel_frank.left(90)
        ebel_frank.forward(50)
        ebel_frank.right(90)
        ebel_frank.forward(30)
        ebel_frank.right(90)
        ebel_frank.forward(50)
        ebel_frank.left(90)
        ebel_frank.forward(20)
        ebel_frank.left(90)
        ebel_frank.forward(120)
        ebel_frank.left(90)
        ebel_frank.forward(20)
        ebel_frank.left(90)
        ebel_frank.forward(50)
        ebel_frank.right(90)
        ebel_frank.forward(30)
        ebel_frank.right(90)
        ebel_frank.forward(50)
        ebel_frank.left(90)
        ebel_frank.forward(20)
        ebel_frank.left(90)
        ebel_frank.forward(120)
        ebel_frank.end_fill()

        ebel_frank.penup()
        ebel_frank.goto(90, 0)
        ebel_frank.pendown()

        ebel_frank.fillcolor("blue")
        ebel_frank.begin_fill()
        ebel_frank.right(180)
        ebel_frank.forward(120)
        ebel_frank.right(90)
        ebel_frank.forward(70)
        ebel_frank.right(90)
        ebel_frank.forward(50)
        ebel_frank.right(90)
        ebel_frank.forward(50)
        ebel_frank.left(90)
        ebel_frank.forward(20)
        ebel_frank.left(90)
        ebel_frank.forward(50)
        ebel_frank.right(90)
        ebel_frank.forward(50)
        ebel_frank.right(90)
        ebel_frank.forward(70)
        ebel_frank.end_fill()

        ebel_frank.penup()
        ebel_frank.goto(110, 20)
        ebel_frank.pendown()

        ebel_frank.fillcolor("white")
        ebel_frank.begin_fill()
        ebel_frank.right(90)
        ebel_frank.forward(10)
        ebel_frank.right(90)
        ebel_frank.forward(30)
        ebel_frank.right(90)
        ebel_frank.forward(10)
        ebel_frank.right(90)
        ebel_frank.forward(30)
        ebel_frank.end_fill()

        ebel_frank.penup()
        ebel_frank.goto(110, 90)
        ebel_frank.pendown()

        ebel_frank.fillcolor("white")
        ebel_frank.begin_fill()
        ebel_frank.right(90)
        ebel_frank.forward(10)
        ebel_frank.right(90)
        ebel_frank.forward(30)
        ebel_frank.right(90)
        ebel_frank.forward(10)
        ebel_frank.right(90)
        ebel_frank.forward(30)
        ebel_frank.end_fill()

        ebel_frank.penup()
        ebel_frank.goto(180, 0)
        ebel_frank.pendown()

        ebel_frank.fillcolor("green")
        ebel_frank.begin_fill()
        ebel_frank.right(90)
        ebel_frank.forward(120)
        ebel_frank.right(90)
        ebel_frank.forward(70)
        ebel_frank.right(90)
        ebel_frank.forward(120)
        ebel_frank.right(90)
        ebel_frank.forward(70)
        ebel_frank.end_fill()

        ebel_frank.penup()
        ebel_frank.goto(200, 20)
        ebel_frank.pendown()

        ebel_frank.fillcolor("white")
        ebel_frank.begin_fill()
        ebel_frank.right(90)
        ebel_frank.forward(80)
        ebel_frank.right(90)
        ebel_frank.forward(30)
        ebel_frank.right(90)
        ebel_frank.forward(80)
        ebel_frank.right(90)
        ebel_frank.forward(30)
        ebel_frank.end_fill()

        ebel_frank.penup()
        ebel_frank.goto(-135, -50)
        ebel_frank.pendown()

        ebel_frank.forward(70)
        ebel_frank.left(90)
        ebel_frank.forward(60)
        ebel_frank.left(90)
        ebel_frank.forward(70)
        ebel_frank.right(90)
        ebel_frank.forward(60)
        ebel_frank.right(90)
        ebel_frank.forward(70)

        ebel_frank.penup()
        ebel_frank.goto(-115, -50)
        ebel_frank.pendown()

        ebel_frank.left(90)
        ebel_frank.forward(120)
        ebel_frank.left(90)
        ebel_frank.forward(70)
        ebel_frank.left(90)
        ebel_frank.forward(120)

        ebel_frank.penup()
        ebel_frank.goto(-25, -170)
        ebel_frank.pendown()

        ebel_frank.forward(120)
        ebel_frank.right(135)
        ebel_frank.forward(169.7056)
        ebel_frank.left(135)
        ebel_frank.forward(120)

        ebel_frank.penup()
        ebel_frank.goto(115, -170)
        ebel_frank.pendown()

        ebel_frank.forward(120)
        ebel_frank.right(90)
        ebel_frank.forward(70)
        ebel_frank.right(90)
        ebel_frank.forward(120)
        ebel_frank.right(90)
        ebel_frank.forward(70)
        ebel_frank.right(180)

        ebel_frank.penup()
        ebel_frank.goto(205, -170)
        ebel_frank.pendown()

        ebel_frank.left(90)
        ebel_frank.forward(120)
        ebel_frank.right(90)
        ebel_frank.forward(70)
        ebel_frank.right(90)
        ebel_frank.forward(120)
        ebel_frank.right(180)
        ebel_frank.forward(60)
        ebel_frank.left(90)
        ebel_frank.forward(70)

        ebel_frank.penup()
        ebel_frank.goto(295, -50)
        ebel_frank.pendown()

        ebel_frank.left(90)
        ebel_frank.forward(60)
        ebel_frank.left(90)
        ebel_frank.forward(35)
        ebel_frank.right(90)
        ebel_frank.forward(60)
        ebel_frank.right(180)
        ebel_frank.forward(60)
        ebel_frank.right(90)
        ebel_frank.forward(35)
        ebel_frank.left(90)
        ebel_frank.forward(60)


MySquare.Square()
